import type { Category } from './entities.js';

// SRS §10. Single source of truth — consumed by seed.ts and system-prompt.ts.
export const CATEGORIES: ReadonlyArray<
  Omit<Category, 'parentCategoryId'> & { parentCategoryId?: string }
> = [
  // Expense
  { categoryId: 'food.dining', name: 'Makan di Luar', nameEn: 'Dining Out', icon: '🍜', type: 'expense' },
  { categoryId: 'food.groceries', name: 'Belanja Dapur', nameEn: 'Groceries', icon: '🛒', type: 'expense' },
  { categoryId: 'food.coffee', name: 'Kopi & Minuman', nameEn: 'Coffee & Drinks', icon: '☕', type: 'expense' },
  { categoryId: 'food.snacks', name: 'Jajanan', nameEn: 'Snacks', icon: '🍪', type: 'expense' },
  { categoryId: 'vehicle.fuel', name: 'Bensin', nameEn: 'Fuel', icon: '⛽', type: 'expense' },
  { categoryId: 'vehicle.parking', name: 'Parkir', nameEn: 'Parking', icon: '🅿️', type: 'expense' },
  { categoryId: 'vehicle.toll', name: 'Tol', nameEn: 'Toll', icon: '🛣️', type: 'expense' },
  { categoryId: 'vehicle.maintenance', name: 'Perawatan Kendaraan', nameEn: 'Vehicle Maintenance', icon: '🔧', type: 'expense' },
  { categoryId: 'vehicle.tax', name: 'Pajak Kendaraan', nameEn: 'Vehicle Tax', icon: '📋', type: 'expense' },
  { categoryId: 'transport.ridehail', name: 'Ojek / Ride-hailing', nameEn: 'Ride-hailing', icon: '🛵', type: 'expense' },
  { categoryId: 'transport.public', name: 'Transportasi Umum', nameEn: 'Public Transport', icon: '🚌', type: 'expense' },
  { categoryId: 'transport.flazz', name: 'Flazz', nameEn: 'Flazz', icon: '💳', type: 'expense' },
  { categoryId: 'transport.taxi', name: 'Taksi', nameEn: 'Taxi', icon: '🚕', type: 'expense' },
  { categoryId: 'shopping.clothing', name: 'Pakaian & Aksesoris', nameEn: 'Clothing & Accessories', icon: '👗', type: 'expense' },
  { categoryId: 'shopping.electronics', name: 'Elektronik', nameEn: 'Electronics', icon: '💻', type: 'expense' },
  { categoryId: 'shopping.personal_care', name: 'Perawatan Diri', nameEn: 'Personal Care', icon: '🧴', type: 'expense' },
  { categoryId: 'shopping.home', name: 'Rumah & Perabot', nameEn: 'Home & Living', icon: '🏠', type: 'expense' },
  { categoryId: 'shopping.online', name: 'Belanja Online', nameEn: 'Online Shopping', icon: '📦', type: 'expense' },
  { categoryId: 'entertainment.streaming', name: 'Streaming', nameEn: 'Streaming', icon: '📺', type: 'expense' },
  { categoryId: 'entertainment.gaming', name: 'Game', nameEn: 'Gaming', icon: '🎮', type: 'expense' },
  { categoryId: 'entertainment.cinema', name: 'Bioskop', nameEn: 'Cinema', icon: '🎬', type: 'expense' },
  { categoryId: 'entertainment.events', name: 'Acara & Hiburan', nameEn: 'Events', icon: '🎉', type: 'expense' },
  { categoryId: 'health.medicine', name: 'Obat-obatan', nameEn: 'Medicine', icon: '💊', type: 'expense' },
  { categoryId: 'health.doctor', name: 'Dokter & Klinik', nameEn: 'Doctor & Clinic', icon: '🏥', type: 'expense' },
  { categoryId: 'health.gym', name: 'Gym & Olahraga', nameEn: 'Gym & Sports', icon: '🏋️', type: 'expense' },
  { categoryId: 'health.insurance', name: 'Asuransi Kesehatan', nameEn: 'Health Insurance', icon: '🩺', type: 'expense' },
  { categoryId: 'health.skincare', name: 'Perawatan Kulit', nameEn: 'Skincare', icon: '✨', type: 'expense' },
  { categoryId: 'bills.electricity', name: 'Listrik', nameEn: 'Electricity', icon: '⚡', type: 'expense' },
  { categoryId: 'bills.internet', name: 'Internet', nameEn: 'Internet', icon: '🌐', type: 'expense' },
  { categoryId: 'bills.phone', name: 'Telepon', nameEn: 'Phone', icon: '📱', type: 'expense' },
  { categoryId: 'bills.water', name: 'Air (PDAM)', nameEn: 'Water', icon: '💧', type: 'expense' },
  { categoryId: 'bills.rent', name: 'Sewa', nameEn: 'Rent', icon: '🏘️', type: 'expense' },
  { categoryId: 'bills.subscription', name: 'Langganan', nameEn: 'Subscription', icon: '🔁', type: 'expense' },
  { categoryId: 'financial.savings', name: 'Tabungan', nameEn: 'Savings', icon: '🏦', type: 'expense' },
  { categoryId: 'financial.investment', name: 'Investasi', nameEn: 'Investment', icon: '📈', type: 'expense' },
  { categoryId: 'financial.loan', name: 'Cicilan', nameEn: 'Loan Payment', icon: '💳', type: 'expense' },
  { categoryId: 'financial.insurance', name: 'Asuransi', nameEn: 'Insurance', icon: '🛡️', type: 'expense' },
  { categoryId: 'education.courses', name: 'Kursus & Pelatihan', nameEn: 'Courses & Training', icon: '📚', type: 'expense' },
  { categoryId: 'education.books', name: 'Buku & Materi', nameEn: 'Books & Materials', icon: '📖', type: 'expense' },
  { categoryId: 'education.school', name: 'Biaya Sekolah', nameEn: 'School Fees', icon: '🎓', type: 'expense' },
  { categoryId: 'life.gifts', name: 'Hadiah', nameEn: 'Gifts', icon: '🎁', type: 'expense' },
  { categoryId: 'life.donations', name: 'Donasi', nameEn: 'Donations', icon: '❤️', type: 'expense' },
  { categoryId: 'life.family', name: 'Tunjangan Keluarga', nameEn: 'Family Support', icon: '👨‍👩‍👧', type: 'expense' },
  { categoryId: 'life.hobbies', name: 'Hobi', nameEn: 'Hobbies', icon: '🎨', type: 'expense' },
  { categoryId: 'life.events', name: 'Acara & Perayaan', nameEn: 'Events & Celebrations', icon: '🥳', type: 'expense' },
  { categoryId: 'life.tobacco', name: 'Tembakau', nameEn: 'Tobacco', icon: '🚬', type: 'expense' },
  { categoryId: 'travel.accommodation', name: 'Akomodasi', nameEn: 'Accommodation', icon: '🏨', type: 'expense' },
  { categoryId: 'travel.flights', name: 'Tiket Pesawat', nameEn: 'Flights', icon: '✈️', type: 'expense' },
  { categoryId: 'travel.activities', name: 'Aktivitas Wisata', nameEn: 'Travel Activities', icon: '🗺️', type: 'expense' },
  { categoryId: 'business.supplies', name: 'Perlengkapan Kantor', nameEn: 'Office Supplies', icon: '🖊️', type: 'expense' },
  { categoryId: 'business.services', name: 'Layanan Bisnis', nameEn: 'Business Services', icon: '💼', type: 'expense' },
  { categoryId: 'other.misc', name: 'Lain-lain', nameEn: 'Miscellaneous', icon: '📌', type: 'expense' },
  // Income
  { categoryId: 'income.salary', name: 'Gaji', nameEn: 'Salary', icon: '💰', type: 'income' },
  { categoryId: 'income.freelance', name: 'Freelance', nameEn: 'Freelance', icon: '🧑‍💻', type: 'income' },
  { categoryId: 'income.investment_return', name: 'Hasil Investasi', nameEn: 'Investment Returns', icon: '📊', type: 'income' },
  { categoryId: 'income.selling', name: 'Penjualan', nameEn: 'Selling', icon: '🏷️', type: 'income' },
  { categoryId: 'income.bonus', name: 'Bonus', nameEn: 'Bonus', icon: '🎯', type: 'income' },
  { categoryId: 'income.other', name: 'Pendapatan Lain', nameEn: 'Other Income', icon: '💵', type: 'income' },
];
